---
kind: pipeline
type: docker
name: default

steps:
- name: build sd image
  image: tinhead/rpi0w-image-builder
  commands:
    - cd /usr/local/buildroot-2019.02.6; FORCE_UNSAFE_CONFIGURE=1 make BR2_EXTERNAL=/usr/local/rpi-sd-builder V=0
    - cp /usr/local/buildroot-2019.02.6/output/images/sdcard.img /drone/src
- name: publish sd image
  image: plugins/github-release
  settings:
    api_key:
      from_secret: github_token
    files: 
      - /drone/src/sdcard.img
    title: Rpi Zero W generig sd image
    checksum:
      - md5